theme: jekyll-theme-cayman
description: A Beauty native Cross Platform Clock Screen Saver for Mac and Windows
show_downloads: "true"
github:
  zip_url: https://github.com/uRyn/uClock/releases
google_analytics: UA-157160560-1
